name: build adocs

on:
  push:
    branches:
    - main
  workflow_dispatch:
permissions:
  id-token: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: asciidoctor
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: build
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor ./resumen.adoc"
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Print hola
      run: echo "hola"
    - name: Print dir
      run: echo "URL:${{ steps.deployment.outputs.page_url }}"
    - name: Print url
      run: ls
