name: ADOC to Github Convert

on:
  push:
    branches:
      - development
    paths:
      - 'documentation/**/*.adoc'
      - '.github/workflows/asciidoc.yml'
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    name: adoc for github
    steps:
      - name: print hola
        run: echo "hola"
